### ISSUE TITLE
Notejot 3.0.0

### ISSUE THREAD

**Issue by lainsce** [lainsce/notejot#227]
# Notejot 3.0.0

A new UI paradigm built on top of what you know and love from Notejot.

![a](https://user-images.githubusercontent.com/4886639/115947035-71bc8b00-a49b-11eb-9049-d96ff2166628.png)

## To-do:

- [x] Port to GTK4.
  - [x] Use flat themed controls. _It's the future._
  - [x] LibHandy → LibAdwaita
- [x] Move note content widget to be a Gtk.TextView instead of a WebKit.WebView.
  - [x] Implement saving/loading rich text formatted contents somehow.
  - [x] Restore List functions
    - [x] Unordered lists with - indicator
    - [x] ~~Ordered lists with numbered rows.~~ Very difficult to implement, skipping.
- [x] Implement formatting keyboard shortcuts.

**Comment by lainsce** [comment]
:tada: DONE!!! :tada:
